on: [push]
name: azure-arm
jobs:
  delete-old-container:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Delete container
      - name: Delete container
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az container delete --name staging --resource-group TestResourceGroup --yes
  
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.RESOURCE_GROUP }}
          template: ./azuredeploy.json
          parameters: imageRegistryPassword=${{ secrets.REGISTRY_PASSWORD }}

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
